### PR TITLE
Added Dockerfile and docker-compose for containerization

### PR DESCRIPTION
**Pull request by mocdaniel**
Since I wanted to run this handy start page from a containerized environment, I created this `Dockerfile` and `docker-compose` for others to use. I also added documentation to `README.md`.

### CODE REVIEW

**Comment by mocdaniel** [comment]
Noticed a strange bug, gonna reopen once I fixed it :)

**Comment by mocdaniel** [comment]
This works now.

**Comment by kikiklang** [comment]
Hello, i'm not super familiar with docker but i get your idea and i like it. I don't have much free time currently but i'll dive into docker soon and test your dev. 

thanks for your work! :)

**Comment by mocdaniel** [comment]
Just checked compatibility after the latest changes from PR #6  - everything's still working fine, the container is pulling the source code from `master` anyways.

**Comment by C-Fu** [comment]
+1 for this. @kikiklang a docker image makes it hugely easy for us to deploy pomme. End result will be something like to just run
docker run -d --name pomme -v /path/to/.env:/pomme/.env -p 7000:80 kikiklang/pommepage:latest and we'll be able to open up pomme via http://machineip:7000.
or just run docker-compose up -d in the same directory as the .env and docker-compose.yml file.
Anyways I'm pretty sure someone like you would be able to pick it up in no time :)

**Pull request merged**
